// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bciboexxeayylqcneuqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjaWJvZXh4ZWF5eWxxY25ldXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTAwMjEsImV4cCI6MjA1ODY2NjAyMX0.JLybwqd6EA_bB6ase8v3tQh9nag_XwODTSUzocR8Yi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
